App\Domain\DTO\NewBirdDTO:
    properties:
        name:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addbird']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 50
                maxMessage: "This value is too long"
                groups: ['addbird']
        birthdate:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addbird']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 50
                maxMessage: "This value is too long"
                groups: ['addbird']
        price:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addbird']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 50
                maxMessage: "This value is too long"
                groups: ['addbird']
        description:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addbird']
            - Length:
                min: 10
                minMessage: "This value is too short"
                max: 1000
                maxMessage: "This value is too long"
                groups: ['addbird']
