App\Domain\DTO\NewBirdDTO:
    properties:
        name:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addbird']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addbird']
        birthdate:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addbird']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addbird']
        price:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addbird']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addbird']
        description:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addbird']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 1000
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addbird']
