App\Domain\DTO\NewInfoDTO:
    properties:
        title:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addinfo']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 100
                maxMessage: "This value is too long"
                groups: ['addinfo']
        author:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addinfo']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 50
                maxMessage: "This value is too long"
                groups: ['addinfo']
        image:
            - Image:
                mimeTypes: ['image/jpeg', 'image/png']
                mimeTypesMessage: "This file is not a valid image"
                maxSize: "2M"
                groups: ['addinfo']
        category:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addinfo']
            - Length:
                min: 3
                minMessage: "This value is too short"
                max: 50
                maxMessage: "This value is too long"
                groups: ['addinfo']
        content:
            - NotBlank:
                message: "This entry must be filled !"
                groups: ['addinfo']
            - Length:
                min: 10
                minMessage: "This value is too short"
                max: 1000
                maxMessage: "This value is too long"
                groups: ['addinfo']
