App\Domain\DTO\NewInfoDTO:
    properties:
        title:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addinfo']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 100
                maxMessage: "This value is too long"
                groups: ['addinfo']
        author:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addinfo']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addinfo']
        image:
            - Image:
                mimeTypes: ['image/jpeg', 'image/png']
                mimeTypesMessage: "Ce format d'image est interdit, veuillez recommencer votre saisie."
                maxSize: "2M"
                groups: ['addinfo']
        category:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addinfo']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addinfo']
        content:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addinfo']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 1000
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addinfo']
