App\Domain\DTO\NewNewsDTO:
    properties:
        title:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addnews']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 100
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addnews']
        author:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addnews']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addnews']
        image:
            - Image:
                mimeTypes: ['image/jpeg', 'image/png']
                mimeTypesMessage: "This file is not a valid image"
                maxSize: "2M"
                groups: ['addnews']
        content:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['addnews']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 1000
                maxMessage: "Cette valeur est trop longue !"
                groups: ['addnews']
