App\Domain\DTO\NewReservationFormSubmittedDTO:
    properties:
        name:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['reservation']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['reservation']
        email:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['reservation']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['reservation']
            - Email:
                message: "Cette adresse '{{ value }}' doit être une adresse e-mail valide."
        message:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['reservation']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 1000
                maxMessage: "Cette valeur est trop longue !"
                groups: ['reservation']