App\Domain\DTO\UpdateBirdDTO:
    properties:
        name:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['updatebird']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['updatebird']
        price:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['updatebird']
            - Type:
                type: integer
                message: "Ce champs ne doit contenir que des chiffres, veuillez saisir une valeur correcte."
                groups: ['updatebird']
        description:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['updatebird']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 1000
                maxMessage: "Cette valeur est trop longue !"
                groups: ['updatebird']
