App\Domain\DTO\UserResetPasswordDTO:
    properties:
        username:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['resetpassword']
            - Length:
                min: 3
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['resetpassword']
        email:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['resetpassword']
            - Length:
                min: 10
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['resetpassword']
            - Email:
                message: "Cette adresse '{{ value }}' doit être une adresse e-mail valide."