App\Domain\DTO\UserNewPasswordDTO:
    properties:
        password:
            - NotBlank:
                message: "Ce champs est requis, veuillez saisir une valeur."
                groups: ['resetpassword']
            - Length:
                min: 5
                minMessage: "Cette valeur est trop courte !"
                max: 50
                maxMessage: "Cette valeur est trop longue !"
                groups: ['resetpassword']